# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    # 실제 스케쥴 작업이 시작될 cron을 등록하면 됩니다.
    # 크론은 https://crontab.guru/ 여기서 확인하면 좋을 것 같습니다.
    # 이 크론은 평일 5시 (한국시간 14시)에 실행됩니다.
    - cron: '0 1,13 * * *' # KST 10시, 22시

permissions:
  contents: read

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run
      env: 
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        BASE_URL: ${{ secrets.BASE_URL }}
        STADIUM_GROUP: ${{ secrets.STADIUM_GROUP }}
      run: |
        python main.py
